### ISSUE TITLE
Complie SLAM algorithm without SLAMBench-LSD-SLAM

### ISSUE THREAD

**Issue by yuhaozhang7** [nikolaradulov/slambench#4]
In the CMakeList.txt of lsdslam source code, `generate_slam_library` is not defined.

Solution:
Implement it in a similar way as CMakeList.txt of SLAMBench.
```
SET(SLAMBENCH_C_WRAPPER                            -Wl,--whole-archive slambench-c-wrapper                            -Wl,--no-whole-archive)
SET(NULL_FILE_PATH "/path/to/null.cpp")
function(generate_slam_library library_name )
    add_library(${library_name}-library SHARED ${NULL_FILE_PATH})
    target_link_libraries(${library_name}-library PRIVATE ${SLAMBENCH_C_WRAPPER} ${library_name})
    SET_TARGET_PROPERTIES(${library_name}-library PROPERTIES LINK_FLAGS "${ARGN}")
    install(TARGETS ${library_name}-library  DESTINATION  lib/)
endfunction()
```
In such case, do we need to modify CMakeList.txt of each algorithm?

After implementing `generate_slam_library` , and make sure it can find packages and include correct directories, `cmake ..` will work, but `make` fail because `lsd_slam/lsd_slam_core/src/lsdslamconfig.h` includes `SLAMBenchConfiguration.h`, does it somehow makes it become impossible to generate a library, that can be used by SLAMBench, for each algorithm independently (without using SLAMBench)?

**Comment by Yuhao-Zhang617** [comment]
might not need to change the architecture, just move the compilation proccess into SLAMBench instance, and CMakeLists.txt of algorithms is still looking for packages at the location of deps mounted by volume, which separated from deps of SLAMBench.
Please forgive me if it has already discussed in the meeting, sometimes I can't catch all points when things get complicated in conversation

**Comment by nikolaradulov** [comment]
I think what Mihai was saying in the meeting is that in order to build the algorithm the slambench application itself does not need to be built, but it needs to have access to some of the include files of SLAMBench, for example SLAMBenchConfiguration.h. One way of doing this we discussed in the meeting was to copy the cod of slambench into the container that builds the algorithm volume. Since the container is then discarded after the volume is built moving it along does not become an issue. This could of course mean that we can have it built inside the main container. For now please try on Monday to build the algorithm in the container where the code for salm has been included. I think that means just the framework folder . `You do not need to do `make slambench` in order to build it, as that is not required on compilation of the algorithm.

**Comment by Yuhao-Zhang617** [comment]
Thanks for clarification, but there is another problem. This is what I did
1. clone a new slambench from github
2. `make kfusion` to clone the source code of kfusion
3. go to the source code  `cd slambench/benchmarks/kfusion/src/original`
4. modify the source code as discussed in [](https://github.com/nikolaradulov/slambench/issues/3)
5. define `generate_slam_library` function
```
SET(SLAMBENCH_C_WRAPPER                            -Wl,--whole-archive slambench-c-wrapper                            -Wl,--no-whole-archive)
SET(NULL_FILE_PATH "/path/to/null.cpp")
function(generate_slam_library library_name )
    add_library(${library_name}-library SHARED ${NULL_FILE_PATH})
    target_link_libraries(${library_name}-library PRIVATE ${SLAMBENCH_C_WRAPPER} ${library_name})
    SET_TARGET_PROPERTIES(${library_name}-library PROPERTIES LINK_FLAGS "${ARGN}")
    install(TARGETS ${library_name}-library  DESTINATION  lib/)
endfunction()
```
6. Remove find_package() of Toon and Eigen3
7. `mkdir build && cd build`
8. `cmake .. -DEIGEN3_INCLUDE_DIR=/path/to/eigen3/include/eigen3/ -DTOON_INCLUDE_PATHS=/path/to/toon/include/ -DSLAMBENCH_INCLUDE_DIR=/path/to/slambench/framework/shared/include/`
9. `make` which report an error
```
[ 50%] Linking CXX shared library lib-openmp-library.so
/usr/bin/ld: cannot find -lslambench-c-wrapper
collect2: error: ld returned 1 exit status
```
But `slambench-c-wrapper.a` or `slambench-c-wrapper.dir` are generated after `make slambench`

I tried to remove ${SLAMBENCH_C_WRAPPER} in generated_slam_library, then we are able to generate a library for kfusion, however, it can not be used by slambench, for example `./build/bin/slambench -i datasets/ICL_NUIM/living_room_traj2_loop.slam -load /path/to/new_generated/libkfusion-cpp-library.so --gui true` fail, with message 
```
Parameter input assigned value datasets/ICL_NUIM/living_room_traj2_loop.slam
Parameter load-slam-library assigned value /home/yuhao/slambench/benchmarks/kfusion/src/original/build/libkfusion-cpp-library.so
new library name: /home/yuhao/slambench/benchmarks/kfusion/src/original/build/libkfusion-cpp-library.so
Cannot load symbol c_sb_init_slam_system/home/yuhao/slambench/benchmarks/kfusion/src/original/build/libkfusion-cpp-library.so: undefined symbol: c_sb_init_slam_system
```

**Comment by nikolaradulov** [comment]
If you get a fresh SLAMBench dist outside of the container, and try to build one of the algorithms first does it compile?

So for example: 
```
git clone https://github.com/pamela-project/slambench.git
make open_vins #or another algorithm 
make slambench APPS=openvins
```
From the meeting what I got from Mihai is that you don't need SLAMBench built in order to be able to build the algorithm.

However given the errors you have gotten that makes little sense. I think ''.a'' files refer to static libraries, meaning they need to be present at compilation for the linking. So unless the original build is configured such that when you execute `make slambench APPS` the get build on their own if not present, it would mean that slambench should be compiled before the algorithm.

**Comment by Yuhao-Zhang617** [comment]
`make slambench APPS=kfusion` doesn't work without `make slambench`

If we want to generate library for algorithm independently, one solution I find is to remove `generate_slam_library` function in cmake file of algorithm, use regular cmake and make to generate libkfusion-cpp.a, then mount it to slambench container, and use `generate_slam_library` with `libkfusion-cpp.a` and `libslambench-c-wrapper.a` to generate `libkfuison-cpp-library.so` which can be used by slambench.
